spring.application.name=journal
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://sachinam_db_user:TGTJwoZTlKxZvgBI@cluster0.t123zvi.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journalDb
#spring.data.mongodb.auto-index-creation=true
